get_token:
  description: Get MicroBot token
  fields:
    bdaddr:
      name: bdaddr
      description: Bluetooth address
      required: true
      selector:
        text:
start_server:
  description: Start Server
set_params:
  description: Calibration - Set mode, depth and press&hold duration. Warning - this will send a push to the device
  fields:
    depth:
      name: Depth
      description: Depth (0-100)
      required: true
      selector:
        number:
          mode: slider
          step: 1
          min: 0
          max: 100
    duration:
      name: Duration
      description: Duration in seconds
      required: true
      selector:
        number:
          mode: box
          step: 1
          min: 0
          max: 999999
    mode:
      name: Mode
      description: normal|invert|toggle
      required: true
      selector:
        select:
          options:
            - "normal"
            - "invert"
            - "toggle"
